name: Destroy Pulumi Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Set Up AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Find Pulumi Project
        id: find-project
        run: |
          PROJECT_DIR=$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "::error::No Pulumi.yaml found in repository"
            exit 1
          fi
          echo "PROJECT_DIR=${PROJECT_DIR}" >> $GITHUB_ENV
          echo "Found Pulumi project in: ${PROJECT_DIR}"

      - name: Install Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Destroy Resources
        working-directory: ${{ env.PROJECT_DIR }}
        run: pulumi destroy --yes
