name: Destroy Pulumi Resources

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Set Up AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Find and Select Pulumi Stack
        id: select-stack
        run: |
          # Find the Pulumi project directory
          PROJECT_DIR=$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "::error::No Pulumi.yaml found in repository"
            exit 1
          fi
          echo "PROJECT_DIR=${PROJECT_DIR}" >> $GITHUB_ENV
          
          # Select or create the dev1 stack
          cd "$PROJECT_DIR"
          if ! pulumi stack select dev1 --non-interactive 2>/dev/null; then
            echo "::error::Stack dev1 not found and stack creation disabled for destroy workflow"
            exit 1
          fi

      - name: Install Dependencies
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Destroy Resources
        working-directory: ${{ env.PROJECT_DIR }}
        run: pulumi destroy --yes --skip-preview
