name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This enables manual triggering

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Pulumi Login
        run: pulumi login

      - name: Pulumi Stack Select
        run: pulumi stack select GirishaDaggula/Lab08project/dev --non-interactive

      - uses: pulumi/actions@v5
        with:
          command: up  
          stack-name: GirishaDaggula/Lab08project/dev  # Ensure the correct stack is specified
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pul-82966e759e4d67e8b0ff1a04cbc43c07627c33d7 }}
          # Uncomment if not using Pulumi ESC:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
