name: Pulumi Deployment with OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1
          role-session-name: GitHubActionsPulumiDeploy

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Initialize Pulumi Stack
        run: |
          if ! pulumi stack select dev --non-interactive 2>/dev/null; then
            pulumi stack init dev --non-interactive
          fi
          pulumi config set aws:region us-east-1 --non-interactive
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Create Website Directory
        run: |
          mkdir -p website
          if [ ! -f website/index.html ]; then
            echo '<!DOCTYPE html><html><head><title>Welcome</title></head><body><h1>Welcome</h1></body></html>' > website/index.html
          fi
          if [ ! -f website/error.html ]; then
            echo '<!DOCTYPE html><html><head><title>Error</title></head><body><h1>404</h1></body></html>' > website/error.html
          fi

      - name: Pulumi Preview
        run: pulumi preview --non-interactive

      - name: Pulumi Deploy
        run: pulumi up --yes --skip-preview --non-interactive
