name: Pulumi Deployment with OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true  # Cancel any previous runs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up AWS Credentials with OIDC
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Find and Initialize Stack
        run: |
          PROJECT_DIR=$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)
          cd "$PROJECT_DIR"
          
          # Cancel any in-progress updates
          pulumi cancel --yes 2>/dev/null || true
          
          pulumi login
          if ! pulumi stack select dev --non-interactive; then
            pulumi stack init dev --non-interactive
          fi

      - name: Pulumi Preview
        run: |
          cd "$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)"
          pulumi preview --non-interactive

      - name: Pulumi Deploy
        run: |
          cd "$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)"
          pulumi up --yes --skip-preview --non-interactive
