name: Pulumi Deployment with OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Find Pulumi Project Directory
        id: find-project
        run: |
          PROJECT_DIR=$(find . -name Pulumi.yaml -exec dirname {} \; | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "::error::No Pulumi.yaml found in repository"
            exit 1
          fi
          echo "PROJECT_DIR=${PROJECT_DIR}" >> $GITHUB_ENV
          echo "Found Pulumi project in: ${PROJECT_DIR}"

      - name: Set Up AWS Credentials with OIDC
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh

      - name: Pulumi Preview
        working-directory: ${{ env.PROJECT_DIR }}
        run: pulumi preview

      - name: Pulumi Deploy
        working-directory: ${{ env.PROJECT_DIR }}
        run: pulumi up --yes
