name: Pulumi Deployment with OIDC

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::904233128713:role/git  # Add your role ARN here
          aws-region: us-east-1
          role-session-name: github-actions-${{ github.run_id }}
          audience: sts.amazonaws.com

      - name: Verify AWS credentials
        run: aws sts get-caller-identity
